let testBoard = {
        "0,0":null,
        "1,0":null,
        "4,0":null,
        "5,0":null,
        "0,1":null,
        "1,1":null,
        "3,1":null,
        "4,1":null,
        "5,1":null,
        "0,2":null,
        "1,2":null,
        "3,2":null,
        "4,2":null,
        "5,2":null,
        "0,3":null,
        "1,3":null,
        "2,3":null,
        "4,3":null,
        "5,3":null,
        "0,4":null,
        "1,4":null,
        "2,4":null,
        "4,4":null,
        "5,4":null,
        "0,5":null,
        "1,5":null,
        "4,5":null,
        "5,5":null};
let testDominos = [[0,4], [6,4], [0,2], [3,4], [4,2], [3,3], [0,1], [6,6], [1,5], [3,2], [1,3], [2,2], [0,5], [1,2]];
testDominos = testDominos.slice(0,4);
let testConstraints = [
    {   type: "=",
        value: 0,
        tiles: ["0,0", "1,0"]},
    {   type: "=",
        value: 4,
        tiles: ["0,1", "0,2"]},
    {   type: "==",
        tiles: ["1,1", "1,2", "1,3"]},
    {   type: ">",
        value: 4,
        tiles: ["0,3"]},
    {   type: "=",
        value: 0,
        tiles: ["0,4"]},
    {   type: "==",
        tiles: ["0,5", "1,5", "1,4"]},
    {   type: "=",
        value: 0,
        tiles: ["2,4"]},
    {   type: "<",
        value: 2,
        tiles: ["2,3"]},
    {   type: "==",
        tiles: ["4,0", "5,0", "4,1", "4,2"]},
    {   type: "<",
        value: 2,
        tiles: ["3,1"]},
    {   type: ">",
        value: 2,
        tiles: ["3,2"]},
    {   type: "=",
        value: 18,
        tiles: ["5,1", "5,2", "5,3"]},
    {   type: "=",
        value: 4,
        tiles: ["4,3"]},
    {   type: "=",
        value: 2,
        tiles: ["4,4", "5,4"]},
    {   type: ">",
        value: 4,
        tiles: ["4,5"]}
]

function removeChildren(htmlObject){
    while(htmlObject.firstChild){
        htmlObject.removeChild(htmlObject.firstChild);
    }
}
